# AnyClassifier

In [2]:
import dabl
import openml
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

# set api key
openml.config.apikey = open('.key', 'r').readline().strip('\n')

## Get AutoML Benchmark Tasks

In [2]:
task_ids = [7593, 146818, 168908, 168912, 168910, 168909, 189354, 168911, 189356, 189355, 
            34539, 168868, 3945, 168330, 168337, 168335, 168329, 146606, 168332, 168331, 
            168338, 146212, 146822, 146821, 9981, 10101, 14965, 146195, 9952, 167120, 
            146825, 9977, 7592, 12, 31, 53, 3, 3917, 167119]

## Run and Publish on OpenML

In [ ]:
for i in task_ids:
    
    try:
        # get task
        print('Get task:', i)
        task = openml.tasks.get_task(i)

        # initialize classifier
        clf = make_pipeline(dabl.models.AnyClassifier(force_exhaust_budget=True))

        # run clf on the task
        print('Run clf on the task')
        run = openml.runs.run_model_on_task(clf, task)

        # print feedbackack
        print('Publish openml run...')

        # publish the run
        run.publish()
    
    except Exception as e:
        print('An error occurred...')
        print(e)
        continue
        
    else:
        # print feedback
        print('View run online: https://www.openml.org/r/' + str(run.run_id))
        print()
    
    

In [3]:
task = openml.tasks.get_task(3)
clf = make_pipeline(dabl.models.AnyClassifier(force_exhaust_budget=False))
run = openml.runs.run_model_on_task(clf, task)

/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl/dabl/preprocessing.py:255: UserWarning: Discarding near-constant features: [2, 13, 15, 16, 18, 24, 27, 28, 29]
  near_constant.index[near_constant].tolist()))


best classifier:  HistGradientBoostingClassifier(l2_regularization=10.0, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=20,
                               max_iter=400, max_leaf_nodes=64,
                               min_samples_leaf=5, n_iter_no_change=None,
                               random_state=18316, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0)
best score: 0.972


/miniconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:565: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
/miniconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


ValueError: y contains previously unseen labels: [0.0]

In [2]:
task = openml.tasks.get_task(12)
clf = make_pipeline(dabl.models.AnyClassifier(force_exhaust_budget=False))
run = openml.runs.run_model_on_task(clf, task)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [2]:
# get task
i = 3
print('Get task:', i)
task = openml.tasks.get_task(i)

# initialize classifier
clf = make_pipeline(dabl.models.AnyClassifier(force_exhaust_budget=False))

# run clf on the task
print('Run clf on the task')
run = openml.runs.run_model_on_task(clf, task)

# print feedbackack
print('Publish openml run...')

# publish the run 
run.publish()

Get task: 3
Run clf on the task


/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl/dabl/preprocessing.py:255: UserWarning: Discarding near-constant features: [2, 13, 15, 16, 18, 24, 27, 28, 29]
  near_constant.index[near_constant].tolist()))


best classifier:  HistGradientBoostingClassifier(l2_regularization=1e-06, learning_rate=0.1,
                               loss='auto', max_bins=128, max_depth=12,
                               max_iter=300, max_leaf_nodes=4,
                               min_samples_leaf=3, n_iter_no_change=None,
                               random_state=28019, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0)
best score: 0.959


IndexError: boolean index did not match indexed array along dimension 1; dimension is 36 but corresponding boolean dimension is 27

In [11]:
# get task
i = 3
print('Get task:', i)
task = openml.tasks.get_task(i)

# initialize classifier
clf = make_pipeline(dabl.models.AnyClassifier(force_exhaust_budget=False))

# run clf on the task
print('Run clf on the task')
run = openml.runs.run_model_on_task(clf, task)

# print feedbackack
print('Publish openml run...')

# publish the run 
run.publish()

Get task: 3
Run clf on the task
best classifier:  HistGradientBoostingClassifier(l2_regularization=1e-05, learning_rate=0.1,
                               loss='auto', max_bins=32, max_depth=10,
                               max_iter=350, max_leaf_nodes=8,
                               min_samples_leaf=2, n_iter_no_change=None,
                               random_state=65502, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0)
best score: 0.978


/miniconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:565: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
/miniconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


ValueError: y contains previously unseen labels: [0.0]

## Run and Save Results Locally

In [ ]:
for i in task_ids:
    
    try:

        # get task
        task = openml.tasks.get_task(i)

        # get dataset object 
        data = openml.datasets.get_dataset(task.dataset_id)

        # get relevant info from dataset object
        X, y, categorical_indicator, attribute_names = data.get_data(dataset_format='dataframe',
                                                                    target=data.default_target_attribute)

        sr = dabl.models.AnyClassifier(force_exhaust_budget=False)
        sr.fit(X, y)
        
        sr.best_

In [5]:
# get task
task = openml.tasks.get_task(15)

# get dataset object 
data = openml.datasets.get_dataset(task.dataset_id)

# get relevant info from dataset object
X, y, categorical_indicator, attribute_names = data.get_data(dataset_format='array',
                                                            target=data.default_target_attribute)

sr = dabl.models.AnyClassifier(force_exhaust_budget=False)
sr.fit(X, y)

best classifier:  HistGradientBoostingClassifier(l2_regularization=10.0, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=20,
                               max_iter=400, max_leaf_nodes=64,
                               min_samples_leaf=5, n_iter_no_change=None,
                               random_state=18316, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0)
best score: 0.967


AnyClassifier(force_exhaust_budget=False, n_jobs=None, verbose=0)

In [13]:
# get task
task = openml.tasks.get_task(3)

# get dataset object 
data = openml.datasets.get_dataset(task.dataset_id)

# get relevant info from dataset object
X, y, categorical_indicator, attribute_names = data.get_data(dataset_format='array',
                                                            target=data.default_target_attribute)

y = y.astype('str')

sr = dabl.models.AnyClassifier(force_exhaust_budget=False)

cross_val_score(sr, X = X, y = y, scoring = 'roc_auc', cv = 3)

/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl/dabl/preprocessing.py:255: UserWarning: Discarding near-constant features: [2, 13, 16, 18, 24, 27, 28]
  near_constant.index[near_constant].tolist()))


KeyboardInterrupt: 

In [13]:
X, y = datasets.load_breast_cancer(return_X_y=True)
lr = LogisticRegression()
cross_val_score(lr, X = X, y = y, scoring = 'roc_auc', cv = 2)

/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.992885  , 0.98929404])

In [22]:
lr.fit(X, y).predict_proba(X)

/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([[1.00000000e+00, 2.12347678e-15],
       [9.99999982e-01, 1.81026586e-08],
       [9.99999964e-01, 3.56495651e-08],
       ...,
       [9.98224922e-01, 1.77507767e-03],
       [1.00000000e+00, 5.88460213e-11],
       [3.43074915e-02, 9.65692509e-01]])

In [ ]:
roc_auc_score_auc_score()

In [25]:
sr.fit(X, y)
sr.predict_proba(X)

array([[9.99993492e-01, 6.50767554e-06],
       [9.99998767e-01, 1.23289966e-06],
       [9.99999843e-01, 1.57469379e-07],
       ...,
       [9.99997267e-01, 2.73345748e-06],
       [9.99999851e-01, 1.49164405e-07],
       [7.44596422e-07, 9.99999255e-01]])

In [27]:
X, y = datasets.load_breast_cancer(return_X_y=True)
sr = dabl.models.AnyClassifier(force_exhaust_budget=False)
sr.fit(X, y)
sr.predict_proba(X)

best classifier:  HistGradientBoostingClassifier(l2_regularization=1e-05, learning_rate=0.1,
                               loss='auto', max_bins=32, max_depth=10,
                               max_iter=350, max_leaf_nodes=8,
                               min_samples_leaf=2, n_iter_no_change=None,
                               random_state=65502, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0)
best score: 0.978


array([[9.99999597e-01, 4.02581127e-07],
       [9.99999566e-01, 4.34470862e-07],
       [9.99999986e-01, 1.38177289e-08],
       ...,
       [9.99999925e-01, 7.47631129e-08],
       [9.99999993e-01, 6.77204444e-09],
       [9.81074925e-07, 9.99999019e-01]])

In [2]:
X, y = datasets.load_breast_cancer(return_X_y=True)
sr = dabl.models.AnyClassifier(force_exhaust_budget=False)
cross_val_score(sr, X = X, y = y, scoring = 'roc_auc', cv = 2)

best classifier:  SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.03162277660168379,
    kernel='rbf', max_iter=-1, probability=True, random_state=1, shrinking=True,
    tol=0.001, verbose=False)
best score: 0.953
best classifier:  HistGradientBoostingClassifier(l2_regularization=1.0, learning_rate=0.1,
                               loss='auto', max_bins=32, max_depth=18,
                               max_iter=450, max_leaf_nodes=128,
                               min_samples_leaf=5, n_iter_no_change=None,
                               random_state=13317, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0)
best score: 0.948


array([0.98956467, 0.99046004])

In [3]:
X, y = datasets.load_breast_cancer(return_X_y=True)

sr = dabl.models.AnyClassifier(force_exhaust_budget=False)

cross_val_score(sr, X = X, y = y, scoring = 'roc_auc', cv = 2)

KeyboardInterrupt: 

In [6]:
# get task
task = openml.tasks.get_task(6)

# get dataset object 
data = openml.datasets.get_dataset(task.dataset_id)

# get relevant info from dataset object
X, y, categorical_indicator, attribute_names = data.get_data(dataset_format='array',
                                                            target=data.default_target_attribute)

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [7]:
sr = dabl.models.AnyClassifier(force_exhaust_budget=False)
# sr = LogisticRegression()
sr.fit(X_train, y_train)

/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


KeyboardInterrupt: 

In [31]:
sr.score

<bound method ClassifierMixin.score of AnyClassifier(force_exhaust_budget=False, n_jobs=None, verbose=0)>

In [32]:
y_pred = sr.predict(X_test)

/miniconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:565: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
/miniconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


ValueError: y contains previously unseen labels: [0.0]

In [ ]:
roc_auc_score()

In [3]:
# get task
task = openml.tasks.get_task(3)

# get dataset object 
data = openml.datasets.get_dataset(task.dataset_id)

# get relevant info from dataset object
X, y, categorical_indicator, attribute_names = data.get_data(dataset_format='array',
                                                            target=data.default_target_attribute)

sr = dabl.models.AnyClassifier(force_exhaust_budget=True)
sr.fit(X, y)

/Users/hp2500/Google Drive/STUDY/Columbia/Research/dabl/dabl/preprocessing.py:255: UserWarning: Discarding near-constant features: [2, 13, 15, 16, 18, 24, 27, 28, 29]
  near_constant.index[near_constant].tolist()))


best classifier:  HistGradientBoostingClassifier(l2_regularization=1e-05, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=16,
                               max_iter=400, max_leaf_nodes=64,
                               min_samples_leaf=10, n_iter_no_change=None,
                               random_state=58027, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0)
best score: 0.978
test test test loool lehl


AnyClassifier(force_exhaust_budget=True, n_jobs=None, verbose=0)